document.write( '<h1>Guess The Number</h1> \n' );
document.write( '  \n' );
document.write( '<p> Can you guess the number between 1-100? Play to see how many guesses you get!</p> \n' );
document.write( '  \n' );
document.write( '<div class=\"form\"> \n' );
document.write( '    <label for=\"guessField\">Enter a guess: </label> \n' );
document.write( '    <input type = \"text\" id = \"guessField\" class = \"guessField\"> \n' );
document.write( '    <input type = \"submit\" value = \"Try\" \n' );
document.write( '           class = \"guessSubmit\" id = \"submitguess\"> \n' );
document.write( '</div> \n' );
document.write( '  \n' );
document.write( '<script type = \"text/javascript\"> \n' );
document.write( '    var y = Math.floor(Math.random() * 100 + 1); \n' );
document.write( '    var guess = 1; \n' );
document.write( '      \n' );
document.write( '    document.getElementById(\"submitguess\").onclick = function(){      \n' );
document.write( '    var x = document.getElementById(\"guessField\").value; \n' );
document.write( '  \n' );
document.write( '   if(x == y) \n' );
document.write( '   {    \n' );
document.write( '       alert(\"CONGRATULATIONS!!! You guessed it in \"\n' );
document.write( '               + guess + \" guesses! \"); \n' );
document.write( '   } \n' );
document.write( '   else if(x > y) \n' );
document.write( '   {     \n' );
document.write( '       guess++; \n' );
document.write( '       alert(\"Try a lower number!\"); \n' );
document.write( '   } \n' );
document.write( '   else\n' );
document.write( '   { \n' );
document.write( '       guess++; \n' );
document.write( '       alert(\"Try a higher number!\") \n' );
document.write( '   } \n' );
document.write( '} ' );
